
server:
   port: 8096

     
   spring:
      cloud:
       config:
        server:
            git:
             url:https://github.com/MEgusquiza/ProyectoReactivoEveris.git
             searchPath:config_data
             username:${GIT_USER}
             password:${GIT_PASSWORD}
