server:
   port: 8096
            
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MEgusquiza/ConfigDataEveris.git 
          searchPaths: ConfigDataEveris
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
